spring:
  datasource:
    url: ${AWS_RDS_DEV}
    username: ${AWS_RDS_DEV_USERNAME}
    password: ${AWS_RDS_DEV_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: pickple.back.batch
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
  type-handlers-package: pickple.back.batch

